[tool.poetry]
name = "CadastralDataAnalyser"
version = "0.1.0"
description = ""
authors = ["bdaniere <benjamin.daniere@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.14.0"
geopandas = "^1.1.4"
requests = "^2.34.2"
psycopg2-binary = "^2.9.12"
geoalchemy2 = "^0.20.0"
sqlalchemy = "^2.0.52"
python-dotenv = "^1.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 95